CREATE TABLE IF NOT EXISTS NOTES (
url TEXT PRIMARY KEY,
color TEXT,
pin INT
);

CREATE TABLE IF NOT EXISTS NOTES_SYNC (
id TEXT,
server TEXT,
user TEXT,
stamp TEXT,
PRIMARY KEY(server, stamp),
FOREIGN KEY(id) REFERENCES NOTES(url)
);

CREATE TABLE IF NOT EXISTS BOOKS (
url TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS BOOKLETS (
book TEXT,
url TEXT,
PRIMARY KEY(url, book),
FOREIGN KEY(book) REFERENCES BOOKS(url)
);

CREATE TABLE IF NOT EXISTS BOOKLETS_SYNC (
id TEXT,
server TEXT,
user TEXT,
stamp TEXT,
PRIMARY KEY(server, stamp),
FOREIGN KEY(id) REFERENCES BOOKLETS(url)
);

CREATE TABLE IF NOT EXISTS LINKS (
url TEXT PRIMARY KEY,
title TEXT,
preview TEXT,
color TEXT,
pin INT,
adddate DATE,
modified DATE
);
